### PR TITLE
Fix comments at start of indented blocks.

### LINKED ISSUE #102: Comments in action rules
Following up on #81/#85, it'd be handy to be able to insert comments throughout an action string, e.g.,

```
# explanation of this block
# explanation of this condition
ifmax ...:
    # explanation of this rule
    x -> y
    # explanation of this rule
    y -> z
# explanation of this condition
elifmax 
    ...

# explanation of this block
ifmax ...:
    ...
```

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
Fixes #102.

**Interactions with other PRs:**
none

**How has this been tested?**
added test case

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- Bug fix (non-breaking change which fixes an issue)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [n/a] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] I have run the test suite locally and all tests passed.

**Still to do:**

### CODE REVIEW

**Comment by drasmuss** [comment]
This fails for
```
    with nengo_spa.Network() as net:
        a = nengo_spa.State(16)
        b = nengo_spa.State(16)
        c = nengo_spa.State(16)
        d = nengo_spa.State(16)

        nengo_spa.Actions("""
            ifmax dot(a, b):
                c -> d
                # comment
            elifmax dot(c, d):
                a -> b
            """)
```
traceback:
```
Traceback (most recent call last):
  File "d:\documents\nengo_spa\nengo_spa\actions.py", line 84, in Actions
    parse_tree = parse(actions)
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 34, in parse
    BytesIO(code.encode()).readline)))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 159, in read
    match.extend(action.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 285, in read
    match.extend(self.rule.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 148, in read
    raise RuleMismatchError(self, self, tokens.peek()[0])
nengo_spa.compiler.parsing.RuleMismatchError: Could not apply rule ''->''. Expected ''->'', but found 'TokenInfo(type=6 (DEDENT), string='', start=(5, 12), end=(5, 12), line='            elifmax dot(c, d):\n')'.
```

**Comment by jgosmann** [comment]
Should be fixed.

**Comment by drasmuss** [comment]
Another failure case:
```
    with nengo_spa.Network() as net:
        a = nengo_spa.State(16)
        b = nengo_spa.State(16)
        c = nengo_spa.State(16)
        d = nengo_spa.State(16)

        nengo_spa.Actions("""
            ifmax dot(a, b):
                c -> d
            elifmax dot(c, d):
                a -> b
            # comment
            
            ifmax dot(a, b):
                c -> d
            elifmax dot(c, d):
                a -> b
            """)
```
```
Traceback (most recent call last):
  File "d:\documents\nengo_spa\nengo_spa\actions.py", line 84, in Actions
    parse_tree = parse(actions)
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 34, in parse
    BytesIO(code.encode()).readline)))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 160, in read
    match.extend(action.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 316, in read
    match.extend(self.rule.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 285, in read
    match.extend(self.rule.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 148, in read
    raise RuleMismatchError(self, self, tokens.peek()[0])
nengo_spa.compiler.parsing.RuleMismatchError: Could not apply rule ''->''. Expected ''->'', but found 'TokenInfo(type=6 (DEDENT), string='', start=(8, 12), end=(8, 12), line='            ifmax dot(a, b):\n')'.
```

**Comment by Seanny123** [comment]
Just leaving a remind to myself to also test the case:
```
    with nengo_spa.Network() as net:
        a = nengo_spa.State(16)
        b = nengo_spa.State(16)
        c = nengo_spa.State(16)
        d = nengo_spa.State(16)

        nengo_spa.Actions("""
            ifmax dot(a, b):
                c -> d
            elifmax dot(c, d):
                a -> b
    # comment
            
            ifmax dot(a, b):
                c -> d
            elifmax dot(c, d):
                a -> b
            """)
```

I'm assuming this gives a reasonable error, but will check the pull request before merging again.

**Comment by jgosmann** [comment]
Should be fixed too. Thanks for finding all of these, @drasmuss!

**Comment by drasmuss** [comment]
Sorry, just thought of one more case, if you put a `# comment` inside a token like 
```
    with nengo_spa.Network() as net:
        a = nengo_spa.State(16)
        b = nengo_spa.State(16)
        c = nengo_spa.State(16)
        d = nengo_spa.State(16)

        nengo_spa.Actions("""
            ifmax dot( 
                    # comment
                    a, b):
                c -> d
            """)
```

However, I think that that is edge-case enough that it'd also be fine to just say we don't support that (unless it's an easy fix).

**Comment by jgosmann** [comment]
Fixed.

**Comment by drasmuss** [comment]
I keep being about to :+1: and then I think of one last case, sorry!  Comments at the end of `ifmax` lines give an error
```
with nengo_spa.Network() as net:
    a = nengo_spa.State(16)
    b = nengo_spa.State(16)
    c = nengo_spa.State(16)
    d = nengo_spa.State(16)

    nengo_spa.Actions("""
        ifmax dot(a, b): # comment
            c -> d
        elifmax dot(c, d):
            a -> b
        """)
```

Again, probably OK to just not support that if it's a troublesome fix.

**Comment by jgosmann** [comment]
> then I think of one last case, sorry!

No need to be sorry about anything, you're just “steel manning” my code so to say. :) Shouldn't be a hard fix either.

The reason why comments give so much “trouble”: They are somewhat orthogonal to the actual grammar in that they can appear in-between a lot of things. Which makes me wonder if including them in the grammar is actually the right approach. Or maybe there is a better way to structure the grammar ... (Also, I'm in the mode of doing the minimal necessary fix each time because I was focusing on other things instead of thoroughly testing comments myself.)

I also broke a test case with my last commit (that surprisingly did not fail locally for me.

**Comment by jgosmann** [comment]
Fixed too.

**Pull request merged**
