### PR TITLE
Fix link in AppVeyor build badge.

### LINKED ISSUE #41: AppVeyor build badge doesn't seem to be working.

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
Fixes #41.

**Interactions with other PRs:**
none

**How has this been tested?**
checked that new link works

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [n/a] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Seanny123** [comment]
Is there any down-side to having the appveyor project under your username?

**Comment by jgosmann** [comment]
idk
@tbekolay?

**Comment by tbekolay** [comment]
No downside that I'm aware of... just means that AppVeyor is using Jan's credentials to access `nengo/nengo_spa` instead of the nengo organization's. I could do it for the nengo org if people prefer, but keeping it this way gives Jan more control over how AppVeyor runs builds etc.

**Comment by Seanny123** [comment]
I'd prefer if you did it with the Nengo org, just for the sake of
consistency.

**Comment by jgosmann** [comment]
I would prefer to keep it how it is for now, so I don't have to bother @tbekolay in case minor changes to the build parameters are necessary. I'm happy to transfer it to the Nengo org once nengo_spa is in a more stable state (or I move on to other things).

**Comment by tbekolay** [comment]
I'd lean on the side of keeping it under Jan for now as well -- I'm not sure if there's a way to transfer ownership through the AppVeyor UI, but it seems like they can do it if you contact support so no harm in changing it later :+1:

**Pull request merged**
